# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'masterplan' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for masterplan
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'JSQMessagesViewController'
  pod 'CircleMenu', '~> 2.0.1'
  pod 'Material', '~> 2.0'
  pod ‘EasyPeasy’
  pod 'Neon'
  pod 'DGElasticPullToRefresh'
  pod 'Eureka'
  pod 'AMTagListView'

  target 'masterplanTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
