# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'masterplan' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for masterplan
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging’
  pod 'CircleMenu', '~> 2.0.1'
  pod 'Eureka’
  pod 'AMTagListView'
  pod 'XLActionController'
  pod 'XLActionController/Periscope'
  pod 'SwiftMessages'
  pod 'Kingfisher', '~> 3.0'
  pod 'MessageKit'

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'MessageKit'
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.0'
                end
            end
        end
    end

  target 'masterplanTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
